import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { GoogleAnalytics } from '@next/third-parties/google'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <div className='main'>
            <div className='gradient'/>
        </div>
        <Navbar />
        {children}
        <Footer />
        </body>
        <GoogleAnalytics gaId='G-EPE5H2NTDE' />
    </html>
    </ClerkProvider>
  )
}
